export type Question = {
  q: string;
  choices: string[];
  answer: number;
  explain: string;
  topic: string;
};

export const questions: Question[] = [
  {
    q: "¿Qué significa la sigla DNS?",
    choices: ["Dynamic Network System", "Domain Name System", "Data Network Service", "Digital Name Server"],
    answer: 1,
    explain: "Qué es: Domain Name System. Por qué existe: para que uses nombres fáciles (google.com) y las máquinas usen IPs. Analogía: guía telefónica — das el nombre, recibes el número.",
    topic: "DNS",
  },
  {
    q: "Escribes un dominio que no existe. ¿Qué tipo de error verás?",
    choices: ["Error HTTP 404", "Error DNS (ERR_NAME_NOT_RESOLVED)", "Error 500", "Error 403"],
    answer: 1,
    explain: "Paso a paso: 1) escribes el dominio 2) el DNS no encuentra la IP 3) la petición ni sale. Por eso NO es 404: el 404 requiere haber llegado al servidor. Analogía: la dirección no está en el mapa — nunca tocaste el timbre.",
    topic: "DNS",
  },
  {
    q: "¿Qué código HTTP significa 'todo bien, éxito'?",
    choices: ["100", "200", "301", "204"],
    answer: 1,
    explain: "Qué es: 200 = OK. Por qué: el servidor SÍ respondió y todo salió bien. Analogía: llegaste a la casa y te abrieron la puerta sin problema.",
    topic: "HTTP",
  },
  {
    q: "El servidor responde con 500. ¿Qué significa?",
    choices: ["El recurso no existe", "No tienes permisos", "Error interno del servidor", "El servidor está saturado"],
    answer: 2,
    explain: "Qué es: 500 = el servidor se rompió por dentro. Por qué importa: sí hubo respuesta (no es DNS). Analogía: llegaste a la casa, pero adentro hubo un accidente.",
    topic: "HTTP",
  },
  {
    q: "¿Cuál es el resultado de: (5 > 2) && !(2 == 4)?",
    choices: ["falso", "verdadero", "error", "5"],
    answer: 1,
    explain: "Paso a paso: 5 > 2 → verdadero. 2 == 4 → falso. !(falso) → verdadero. verdadero && verdadero → verdadero. El ! invierte; el && exige que ambos lados sean sí.",
    topic: "Operadores",
  },
  {
    q: "El operador || (OR) devuelve verdadero cuando…",
    choices: ["ambos lados son verdaderos", "al menos uno es verdadero", "ambos son falsos", "el primero es falso"],
    answer: 1,
    explain: "Qué es: OR = «al menos uno». Por qué: permite alternativas. Analogía de papá: helado si limpias O haces tarea — con una sola basta.",
    topic: "Operadores",
  },
  {
    q: "En la analogía del helado, si mamá dice 'helado SI limpias Y haces tarea', ¿cuándo hay helado?",
    choices: ["Cuando limpias solamente", "Cuando haces tarea solamente", "Solo cuando haces ambas cosas", "Cuando no haces nada"],
    answer: 2,
    explain: "AND (&&) exige las DOS condiciones. Si falta una, no hay helado. Por eso existe &&: para reglas estrictas donde todo debe cumplirse.",
    topic: "Operadores",
  },
  {
    q: "¿Qué comando en Mac/Linux lista los archivos de una carpeta?",
    choices: ["dir", "ls", "list", "show"],
    answer: 1,
    explain: "Qué es: ls = list (listar). Por qué: para ver qué hay en la carpeta actual. Analogía: abrir el cajón y mirar el contenido. En Windows CMD el equivalente es dir.",
    topic: "Terminal",
  },
  {
    q: "Quieres eliminar una carpeta con todo su contenido en Linux. ¿Qué comando usas?",
    choices: ["rmdir carpeta", "rm carpeta", "rm -rf carpeta", "del /s carpeta"],
    answer: 2,
    explain: "Qué es: rm -rf = remove recursive force. Por qué: borrar carpeta + todo lo de adentro. Analogía: tirar la caja entera con todo lo que tiene — y no hay papelera. Úsalo con cuidado.",
    topic: "Terminal",
  },
  {
    q: "¿Qué es HTML?",
    choices: ["Un lenguaje de programación", "Un lenguaje de marcado", "Un framework de JavaScript", "Una hoja de estilos"],
    answer: 1,
    explain: "Qué es: HyperText Markup Language — marcado, no programación. Por qué: etiqueta el contenido («esto es título», «esto es párrafo»). Analogía: etiquetas de mudanza en las cajas.",
    topic: "HTML",
  },
  {
    q: "¿Dónde debe ir todo el contenido visible de una página HTML?",
    choices: ["Dentro de <head>", "Dentro de <body>", "Dentro de <script>", "En cualquier parte"],
    answer: 1,
    explain: "Qué es: body = el escenario visible. Por qué: el navegador espera ahí lo que el usuario ve. Analogía: head es backstage; body es el escenario del teatro.",
    topic: "HTML",
  },
  {
    q: "¿Cuál es la afirmación correcta sobre el DOM?",
    choices: [
      "Es el que dibuja la página en pantalla",
      "Es un árbol de objetos en memoria que permite a JS modificar la página",
      "Es un lenguaje de estilos",
      "Es un tipo de servidor web",
    ],
    answer: 1,
    explain: "Qué es: árbol de objetos en memoria. Por qué existe: para que JS pueda tocar la página en vivo. Quien dibuja es el motor de renderizado. Analogía: la lista del súper pasada a una app editable.",
    topic: "Frontend",
  },
  {
    q: "¿Qué significa mejor la expresión `auto.color`?",
    choices: [
      "El auto que pertenece al color",
      "El color que pertenece al auto",
      "Crear un auto nuevo",
      "Borrar el color",
    ],
    answer: 1,
    explain: "El punto (.) se lee «de» / «su». Antes del punto: la cosa (auto). Después: lo que le pertenece (color). Intención: «quiero el color del auto».",
    topic: "DOM",
  },
  {
    q: "`elemento.textContent` se lee en español como…",
    choices: [
      "Una sola palabra mágica",
      "El texto que pertenece a este elemento",
      "Crear un elemento nuevo",
      "Borrar el HTML",
    ],
    answer: 1,
    explain: "elemento = el cartel. . = de/su. textContent = el texto escrito. Todo junto: «el texto de este elemento». Usalo para leer o cambiar texto.",
    topic: "DOM",
  },
  {
    q: "¿Cómo sabés qué escribir después del punto?",
    choices: [
      "Inventás cualquier palabra",
      "Cada tipo de cosa ya trae herramientas; elegís según la intención (texto→textContent, estilos→style…)",
      "Siempre es .pizza",
      "Solo funciona .id",
    ],
    answer: 1,
    explain: "Como el control remoto de la TV: no inventás botones. Preguntá: ¿qué quiero hacer? → ¿qué herramienta ya existe? textContent, style, classList, value…",
    topic: "DOM",
  },
  {
    q: "En `caja.classList.add('activo')`, ¿qué es `add`?",
    choices: [
      "Una propiedad (características)",
      "Un método (acción) — por eso lleva ()",
      "Un error de sintaxis",
      "El id del elemento",
    ],
    answer: 1,
    explain: "Propiedad = qué tiene (textContent, sin ()). Método = qué puede hacer (add, con ()). add() es una acción: agregar la clase.",
    topic: "DOM",
  },
  {
    q: "¿Qué imprime `console.log(typeof 10);` en JavaScript?",
    choices: ["'Number'", "'number'", "'int'", "10"],
    answer: 1,
    explain: "Qué es: typeof pregunta el tipo. Cómo: siempre responde en minúsculas ('number'). Por qué falla 'Number': JS distingue mayúsculas. Analogía: la etiqueta de categoría del producto.",
    topic: "JS",
  },
  {
    q: "`const precio = 100; precio = 120;` ¿Qué pasa?",
    choices: ["precio vale 120", "precio vale 100", "Lanza TypeError: no se puede reasignar const", "Lanza SyntaxError"],
    answer: 2,
    explain: "Qué es: const = candado permanente. Por qué existe: proteger valores que no deben cambiar. Si necesitas reasignar, usa let. Analogía: frasco sellado vs vaso normal.",
    topic: "JS",
  },
  {
    q: "`'3' * 10` en JavaScript da…",
    choices: ["'310' (texto)", "30 (número)", "NaN", "Error"],
    answer: 1,
    explain: "Paso a paso: con * JS convierte '3' a número y multiplica → 30. Ojo: con + pegaría ('310'). Por eso existe Number('3') cuando quieres sumar de verdad.",
    topic: "JS",
  },
  {
    q: "En `let frutas = ['manzana','pera','uva']`, ¿qué devuelve `frutas[1]`?",
    choices: ["'manzana'", "'pera'", "'uva'", "undefined"],
    answer: 1,
    explain: "Qué representa el índice: la posición del casillero. Empieza en 0: [0]=manzana, [1]=pera, [2]=uva. Analogía: primera taquilla del cine numerada 0.",
    topic: "JS",
  },
  {
    q: "¿Cuál es la diferencia entre `.length` y `.push()` en un array?",
    choices: [
      "Ninguna, son sinónimos",
      ".length es propiedad (sin paréntesis) y .push() es método (con paréntesis)",
      ".length modifica y .push() lee",
      "Ambos son métodos",
    ],
    answer: 1,
    explain: "Qué es cada uno: .length = dato (cuántos hay). .push() = acción (añadir). Por qué los (): los métodos se ejecutan; las propiedades solo se leen. Analogía: cartel «hay 3» vs acción «mete uno más».",
    topic: "JS",
  },
  {
    q: "En `let libro = { titulo: 'El Principito', paginas: 96 }`, ¿cómo lees el título?",
    choices: ["libro[titulo]", "libro.titulo", "libro->titulo", "libro('titulo')"],
    answer: 1,
    explain: "Qué es: notación de punto = leer por etiqueta. Por qué: los objetos usan nombres, no números. Analogía: ficha de biblioteca — buscas «título», no casillero 0.",
    topic: "JS",
  },
  {
    q: "`let arr = [10, 20, 30]; arr.push(40);` ¿Cuánto vale `arr.length` ahora?",
    choices: ["3", "4", "40", "undefined"],
    answer: 1,
    explain: "Paso a paso: había 3 elementos → push añade 40 al final → ahora hay 4. .length cuenta; no es el valor 40. Construyes: primero lista, luego acción push, luego el contador length cambia.",
    topic: "JS",
  },
  {
    q: "¿Qué imprime `console.log('3' - 1);`?",
    choices: ["'2' (texto)", "2 (número)", "'31' (texto)", "NaN"],
    answer: 1,
    explain: "Paso a paso: el operador - pide números → convierte '3' a 3 → 3 - 1 = 2. Con + hubiera pegado ('31'). Mismo valor, distinto operador, distinta intención.",
    topic: "JS",
  },
  {
    q: "¿Cuál es la diferencia entre una propiedad y un método?",
    choices: [
      "Ninguna, se escriben igual",
      "La propiedad se escribe sin () y el método con ()",
      "El método se escribe sin () y la propiedad con ()",
      "Solo cambia el color en el editor",
    ],
    answer: 1,
    explain: "Qué es: propiedad = dato ya conocido; método = acción a ejecutar. Por qué los (): «haz esto ahora». Ejemplo: arr.length vs arr.push(x). Analogía: saber tu edad vs ir a correr.",
    topic: "JS",
  },
  {
    q: "En Mac/Linux, ¿qué comando muestra la ruta de la carpeta actual?",
    choices: ["cd", "ls", "pwd", "dir"],
    answer: 2,
    explain: "Qué es: pwd = Print Working Directory (imprime dónde estás). Por qué: orientarte en el sistema de carpetas. Analogía: mirar el letrero de la calle donde estás parado.",
    topic: "Terminal",
  },
  {
    q: "¿Cuál es el objetivo principal de la Ingeniería de Contexto?",
    choices: [
      "Crear modelos nuevos de IA",
      "Diseñar y organizar la información que recibe el modelo",
      "Programar solo APIs REST",
      "Entrenar redes neuronales desde cero",
    ],
    answer: 1,
    explain: "Qué es: preparar el entorno de información (tarea, rol, datos, historial, herramientas, formato). Por qué: la IA responde según lo que le das, no según lo que vos sabés. Analogía: contratar a alguien con una carpeta completa vs decirle solo «hazlo».",
    topic: "Contexto",
  },
  {
    q: "¿Qué diferencia hay entre Prompt Engineering y Context Engineering?",
    choices: [
      "Son exactamente lo mismo",
      "Prompt = una instrucción puntual; Context = todo el entorno (docs, historial, herramientas, formato…)",
      "Context solo sirve para dibujar",
      "Prompt incluye el hosting",
    ],
    answer: 1,
    explain: "El prompt es la frase. El contexto es el tablero completo. Analogía: pedir el plato vs menú + alergias + ticket anterior + cómo lo querés.",
    topic: "Contexto",
  },
  {
    q: "¿Qué hace RAG (Retrieval-Augmented Generation)?",
    choices: [
      "Entrena el modelo otra vez",
      "Busca información relevante, la agrega al contexto y después responde",
      "Borra el historial del chat",
      "Comprime imágenes",
    ],
    answer: 1,
    explain: "Flujo: pregunta → buscar docs → meter trozo útil en el contexto → generar. No inventa el reglamento: lo lee. Analogía: libro abierto en la página justa.",
    topic: "Contexto",
  },
  {
    q: "Más contexto siempre es mejor. ¿Verdadero o falso en la práctica?",
    choices: ["Verdadero: hay que meter todo", "Falso: importa la relevancia; el ruido y el exceso perjudican", "Solo si usás GPT-4", "Solo en PROD"],
    answer: 1,
    explain: "La ventana de contexto es limitada. Demasiada info o info irrelevante distrae. Relevancia > cantidad. Analogía: mochila chica — 3 páginas útiles > 300 de ruido.",
    topic: "Contexto",
  },
  {
    q: "¿Qué entorno usan los clientes reales?",
    choices: ["DEV", "TEST", "STAGE", "PROD"],
    answer: 3,
    explain: "PROD = producción. Ahí los errores cuestan dinero. DEV es donde vos rompés cosas; STAGE es el ensayo casi igual a PROD.",
    topic: "Deploy",
  },
  {
    q: "¿Qué estrategia de deploy permite volver atrás cambiando el tráfico entre dos copias?",
    choices: ["Recreate", "Rolling", "Blue-Green", "Solo reiniciar el PC"],
    answer: 2,
    explain: "Blue-Green: dos entornos. Cambiás el tráfico a la nueva; si falla, volvés a la vieja. Analogía: dos escenarios y cambiás el reflector.",
    topic: "Deploy",
  },
  {
    q: "¿Qué estrategia libera la nueva versión primero a pocos usuarios?",
    choices: ["Canary", "Recreate", "Apagar el servidor", "STAGE"],
    answer: 0,
    explain: "Canary = prueba con un grupo pequeño. Si va bien, se abre a todos. Analogía: probar el plato nuevo en 5 mesas.",
    topic: "Deploy",
  },
  {
    q: "¿Para qué sirve un archivo .env?",
    choices: [
      "Para guardar secretos (API keys) fuera del código",
      "Para diseñar la interfaz",
      "Para entrenar el modelo",
      "Para cifrar HTTPS automáticamente sin servidor",
    ],
    answer: 0,
    explain: "Las claves no van en el código ni en GitHub. El código lee process.env.NOMBRE. Analogía: la llave en el cajón, no pegada en la puerta.",
    topic: "Deploy",
  },
  {
    q: "¿Qué hace HTTPS respecto a HTTP?",
    choices: [
      "Hace la página más colorida",
      "Cifra la comunicación (candado del navegador)",
      "Elimina la necesidad de hosting",
      "Guarda las API keys en el prompt",
    ],
    answer: 1,
    explain: "HTTPS usa TLS/SSL para cifrar. HTTP manda datos en claro. Analogía: carta en sobre cerrado vs carta abierta.",
    topic: "Deploy",
  },
];
